
package proyecto2datos;

/*Lisandra Agüero Ruíz.
Jose Fabio Alfaro Quesada.
Esteban Espinoza Fallas.
*/


import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class Interfaz extends javax.swing.JFrame {
    private ImplementTree tree;
    
    public Interfaz() {
        tree=new ImplementTree();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boton_insertar = new javax.swing.JButton();
        boton_buscar = new javax.swing.JButton();
        boton_completo = new javax.swing.JButton();
        boton_perfecto = new javax.swing.JButton();
        boton_lleno = new javax.swing.JButton();
        boton_altura = new javax.swing.JButton();
        boton_nivel = new javax.swing.JButton();
        boton_peso = new javax.swing.JButton();
        boton_elimina = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_insertar.setBackground(new java.awt.Color(204, 204, 255));
        boton_insertar.setText("Insertar Libro");
        boton_insertar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_insertarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 113, 36));

        boton_buscar.setBackground(new java.awt.Color(204, 204, 255));
        boton_buscar.setText("Buscar por...");
        boton_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 113, 32));

        boton_completo.setBackground(new java.awt.Color(204, 204, 255));
        boton_completo.setText("Es completo?");
        boton_completo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_completo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_completoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_completo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 113, 30));

        boton_perfecto.setBackground(new java.awt.Color(204, 204, 255));
        boton_perfecto.setText("Es perfecto?");
        boton_perfecto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfectoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_perfecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 113, 30));

        boton_lleno.setBackground(new java.awt.Color(204, 204, 255));
        boton_lleno.setText("Está lleno?");
        boton_lleno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_lleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_llenoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_lleno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 113, 31));

        boton_altura.setBackground(new java.awt.Color(204, 204, 255));
        boton_altura.setText("Altura");
        boton_altura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_alturaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 113, 28));

        boton_nivel.setBackground(new java.awt.Color(204, 204, 255));
        boton_nivel.setText("Niveles");
        boton_nivel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nivelActionPerformed(evt);
            }
        });
        getContentPane().add(boton_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 113, 30));

        boton_peso.setBackground(new java.awt.Color(204, 204, 255));
        boton_peso.setText("Peso");
        boton_peso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pesoActionPerformed(evt);
            }
        });
        getContentPane().add(boton_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 113, 31));

        boton_elimina.setBackground(new java.awt.Color(204, 204, 255));
        boton_elimina.setText("Eliminar por...");
        boton_elimina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminaActionPerformed(evt);
            }
        });
        getContentPane().add(boton_elimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 113, 31));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apple-icon-60x60.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 70, 70));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VERIDIS QUO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descarga (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 250));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 0, 19, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_perfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfectoActionPerformed
         if(tree.complete()){
            JOptionPane.showMessageDialog(null,"El arbol es perfecto");
        }
        else{
            JOptionPane.showMessageDialog(null,"El arbol no es perfecto");
        }
    }//GEN-LAST:event_boton_perfectoActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
       
              String[] options=new String[]{"Autor","Tipo", "Nombre","Codigo"};
        int response=JOptionPane.showOptionDialog(null,"Opciones","MODO BUSQUEDA",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options,options[0]);
        try{
        switch(response){
            case 0: String cod=JOptionPane.showInputDialog(null, "Ingrese el autor", null); 
                   tree.searchA(cod);
                   break;
                     
            case 1: int ty=Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el tipo", null));
                    tree.searchTy(ty);
                    break;
            
            
            case 2: String cad=JOptionPane.showInputDialog(null, "Ingrese el nombre del libro", null);
            tree.searchNa(cad);
            break;
           
            
            case 3: String cud=JOptionPane.showInputDialog(null, "Ingrese el codigo", null);
            tree.searchCo(cud);
            break;
           
               
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al Buscar");
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_alturaActionPerformed
        if(tree.Hight()!=-1){
        JOptionPane.showMessageDialog(null,"La altura es de: "+tree.Hight());
        }
        else{
            JOptionPane.showMessageDialog(null,"El arbol esta vacio");
        }
    }//GEN-LAST:event_boton_alturaActionPerformed

    private void boton_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pesoActionPerformed
        JOptionPane.showMessageDialog(null,"El peso es de: "+tree.weight());
    }//GEN-LAST:event_boton_pesoActionPerformed

    private void boton_nivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nivelActionPerformed
        if(tree.level()==-2){
        JOptionPane.showMessageDialog(null,"El arbol esta vacio");
        }
        else{
            JOptionPane.showMessageDialog(null,tree.level());
        }
    }//GEN-LAST:event_boton_nivelActionPerformed

    private void boton_llenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_llenoActionPerformed
       
        if(tree.full()){
            JOptionPane.showMessageDialog(null,"El arbol es lleno");
        }
        else{
            JOptionPane.showMessageDialog(null,"El arbol no es lleno");
        }
       
    }//GEN-LAST:event_boton_llenoActionPerformed

    private void boton_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_insertarActionPerformed
      try{
        InterfazA in=new InterfazA();
       in.setVisible(true);
       tree.insert(in.getBook());
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "No se pudo ingresar");
      }
    }//GEN-LAST:event_boton_insertarActionPerformed

    private void boton_eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminaActionPerformed
        String[] options=new String[]{"Codigo","Tipo"};
        int response=JOptionPane.showOptionDialog(null,"Opciones","MODO ELIMINA",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options,options[0]);
        try{
        if(response==0){
            String cod=JOptionPane.showInputDialog(null, "Ingrese el codigo", null);
            tree.delete_code(cod);
        }
        else{
             int ty=Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Tipo", null));
             tree.delete_type(ty);
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al eliminar");
        }
    }//GEN-LAST:event_boton_eliminaActionPerformed

    private void boton_completoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_completoActionPerformed
        if(tree.complete()){
            JOptionPane.showMessageDialog(null,"El arbol es completo");
        }
        else{
            JOptionPane.showMessageDialog(null,"El arbol no es completo");
        }
    }//GEN-LAST:event_boton_completoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            tree.writeToFile("Arbol.txt", tree.avl.list);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_altura;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_completo;
    private javax.swing.JButton boton_elimina;
    private javax.swing.JButton boton_insertar;
    private javax.swing.JButton boton_lleno;
    private javax.swing.JButton boton_nivel;
    private javax.swing.JButton boton_perfecto;
    private javax.swing.JButton boton_peso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
